### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by Helveg** [tommybananas/finale#60]
I swear that when I threw any kind of `Error` from inside my middleware, before I went to bed, would result in it being caught by Finale and Finale sending back a JSON response, and terminating the middleware chain.

But today the chain continues even when my auth middleware throws a generic `Error` and I am met with:

```
(node:18540) UnhandledPromiseRejectionWarning: Error: You must send an Authorization header
    at verifyToken (C:\Users\robin\Documents\GIT\bergmann\auth.js:10:29)
    at List.finaleMiddleware (C:\Users\robin\Documents\GIT\bergmann\auth.js:32:5)
    at runHookFunction (C:\Users\robin\Documents\GIT\bergmann\node_modules\finale-rest\lib\Controllers\base.js:147:44)
    at tryCatcher (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues (C:\Users\robin\Documents\GIT\bergmann\node_modules\bluebird\js\release\async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:18540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Helveg** [comment]
It was because I refactored and didn't `await` for the subfunction so it started another Promise.
