### ISSUE TITLE
TypeError: restify.queryParser is not a function

### ISSUE THREAD

**Issue by anuxs** [tommybananas/finale#7]
Code like this:
`var restify = require('restify');
app = server = restify.createServer()
app.use(restify.queryParser());
app.use(restify.bodyParser());`

get an error :
> app.use(restify.queryParser());
                ^

TypeError: restify.queryParser is not a function
    at Object.<anonymous> (/Users/xxxxxxx/sequelize/finale.js:34:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by tommybananas** [comment]
This is not a finale issue

**Comment by anuxs** [comment]
But it was writed in your Getting Started doc .

**Comment by tommybananas** [comment]
Likely a local problem, the restify tests are passing
